export const DANG_NHAP_ACTION = "DANG_NHAP_ACTION";
export const SET_THONG_TIN_NGUOI_DUNG = "SET_THONG_TIN_NGUOI_DUNG";
export const LAY_THONG_TIN_NGUOI_DUNG = "LAY_THONG_TIN_NGUOI_DUNG";
export const LAY_THONG_TIN_TAI_KHOAN = "LAY_THONG_TIN_TAI_KHOAN";
